# Repair the plant genus/family classification -------------------------------
#
# Commit a0f8543 appended genus/family pairs taken from an earlier version of
# the Carruthers et al. plant phylogeny with a plain bind_rows(). Of the 346
# rows it added, 335 were for genera that already had a family and were added
# under a different family concept (Hyacinthaceae for Asparagaceae,
# Chenopodiaceae for Amaranthaceae, Hydrophyllaceae for Boraginaceae,
# Adoxaceae for Viburnaceae, ...). A few were plainly wrong: Senegalia ->
# Clostridiaceae and Buchnera -> Erwiniaceae are bacterial families picked up
# by name matching.
#
# `sp_list_df()` left-joins the species list to `classifications` by genus, so a
# genus carrying two families returns two rows per species. Downstream this
# grafted some species onto the mega-tree twice, reported others as having no
# co-family species in the mega-tree while they had in fact been grafted, and
# shifted the tip labels of several hundred grafted tips onto wrong branches.
#
# This script undoes the whole of that import and then re-adds only what the
# current Carruthers taxonomy (carruthers_taxonomy.rds) contributes that we do
# not already have. We follow WCVP for family circumscription, so where the two
# sources disagree for a genus we already know, ours wins and nothing changes.
# It is idempotent: running it twice gives the same result.

library(dplyr)

load("data/classifications.rda")

# -- 1. undo the old Carruthers import ---------------------------------------
# the 335 rows it added for genera that already had a family; the file lists
# the family removed and the one kept, and was generated by diffing a0f8543
# against its parent commit
dropped <- read.csv("data-raw/carruthers_duplicate_genus_dropped.csv")

# the 11 genera it added that were genuinely new at the time
old_carruthers_genera <- c(
  "Astyria", "Cabari", "Holostylis", "Lysiandra", "Schizostigma",
  "Stelmocrypton", "Talbotia", "Tarenaya", "Tehuasca", "Vuhuangia", "Yildirimlia"
)

classifications <- classifications |>
  anti_join(
    transmute(dropped, taxon = "plant", genus, family = family_dropped),
    by = c("taxon", "genus", "family")
  ) |>
  filter(!(taxon == "plant" & genus %in% old_carruthers_genera))

# -- 2. family overrides -----------------------------------------------------
# Where the current Carruthers taxonomy disagrees with ours we keep ours, since
# we follow WCVP for family circumscription. Almost all 73 disagreements are
# Carruthers using a broader family than PPG I / APG IV does (Polypodiaceae,
# Aspleniaceae and Cyatheaceae in the broad sense across the ferns;
# Chenopodiaceae, Hyacinthaceae, Hydrophyllaceae, Viscaceae and the other
# Santalales and Boraginales segregates), and there our family is the accepted
# one. The genera below are the exceptions, where Carruthers is right and the
# family we inherited is either a homonym mismatch or out of date.
overrides <- read.csv("data-raw/family_overrides.csv")

stopifnot(all(overrides$genus %in% classifications$genus[classifications$taxon == "plant"]))
idx <- match(overrides$genus, with(classifications, ifelse(taxon == "plant", genus, NA)))
classifications$family[idx] <- overrides$family

# -- 3. add what the current Carruthers taxonomy has and we do not ------------
car <- readRDS("data-raw/carruthers_taxonomy.rds") |>
  # 47 tips have no family; older builds of the file store that as the literal
  # string "NA" rather than a real NA, so drop both spellings
  filter(!is.na(family), family != "NA") |>
  distinct(genus, family)

# 49 genera are listed under two families within the Carruthers file itself
# (Dryopteris in both Polypodiaceae and Dryopteridaceae, Muscari in both
# Asparagaceae and Hyacinthaceae, ...). None of them is new to us, but skip
# them explicitly so an ambiguous genus can never be introduced.
ambiguous <- car |> count(genus) |> filter(n > 1) |> pull(genus)

car_new <- car |>
  filter(!genus %in% ambiguous) |>
  anti_join(filter(classifications, taxon == "plant"), by = "genus") |>
  transmute(genus, family, taxon = "plant")

message(nrow(car_new), " genera added from carruthers_taxonomy.rds: ",
        paste(car_new$genus, collapse = ", "))

classifications <- bind_rows(classifications, car_new)

# -- 4. drop genus rows that can never be used -------------------------------
# rtrees pulls the genus out of a species label with ^([-A-Za-z]*)_, so a genus
# name holding a multiplication sign (the nothogenera, "\u00d7Butyagrus") or a
# diaeresis ("Diplo\u00f6n") can never be matched: the regex fails and the whole
# label falls through. Every one of these except Leptochlo\u00f6psis already has an
# ASCII-spelled row carrying the identical family, so the odd-spelled row is
# redundant and is dropped; Leptochlo\u00f6psis has no twin, so it is renamed rather
# than lost. Crepi-Hieracium is left alone: it parses fine.
ascii_genus <- function(x) chartr("\u00e4\u00eb\u00ef\u00f6\u00fc", "aeiou", sub("^\u00d7", "", x))

is_plant <- classifications$taxon == "plant"
special <- is_plant & grepl("[^-A-Za-z]", classifications$genus)
twin <- match(
  paste(ascii_genus(classifications$genus[special]), classifications$family[special]),
  paste(classifications$genus[is_plant], classifications$family[is_plant])
)
# same genus and same family already present under an ASCII spelling -> redundant
drop_special <- which(special)[!is.na(twin)]
# no twin -> keep the row but give it a spelling the parser can read
rename_special <- which(special)[is.na(twin)]
classifications$genus[rename_special] <- ascii_genus(classifications$genus[rename_special])
classifications <- classifications[-drop_special, ]

# parsing artefacts rather than genus names
junk_genera <- c("X", "diospyros", "immaculatae")

# "Incertae_sedis" is a placeholder, not a family: it matches nothing in any
# mega-tree, so these rows cannot graft a species and only make the failure
# report as "no co-family species" instead of "genus not in the database"
classifications <- classifications |>
  filter(!(taxon == "plant" & (genus %in% junk_genera | family == "Incertae_sedis")))

# -- 5. tidy and check -------------------------------------------------------
classifications <- classifications |>
  arrange(taxon, genus) |>
  distinct()

# one family per genus within each taxon group; sp_list_df() relies on this to
# return exactly one row per species
stopifnot(!any(duplicated(classifications[, c("taxon", "genus")])))

usethis::use_data(classifications, overwrite = TRUE, compress = "xz")
