#' Mega-tree of plants based on Open Tree of Life
#' 
#' This tree was based on Brown and Smith (2018), which in turn was based on the Open Tree of Life. 
#' It was copied from `V.PhyloMaker::GBOTB.extended`. After then, node labels were added for empty ones.
#'
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_plant_GBOTB$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source <https://github.com/jinyizju/V.PhyloMaker/tree/master/data>
#' @references Smith, S. A., & Brown, J. W. (2018). Constructing a broadly inclusive seed plant phylogeny. American Journal of Botany, 105(3), 302-314.
#' 
#' Jin, Y., & Qian, H. (2019). V. PhyloMaker: an R package that can generate very large phylogenies for vascular plants. Ecography.
#' 
"tree_plant_GBOTB"


#' Classifications of species
#' 
#' @description 
#' Genus and family information of different groups of taxon. 
#' 
#' - Plant classification information was based on The Plant List. It was generated 
#' based on `V.PhyloMaker::nodes.info.1` with two additions: genus Malaisia (Euphorbiaceae) 
#' and Lithraea (Anacardiaceae). There are 10,606 genus in this file.
#' <https://github.com/jinyizju/V.PhyloMaker/tree/master/data>
#' 
#' - Fish classification information was based on FishBase. There are 4,825 genus in this file.
#' <https://fishtreeoflife.org/downloads/PFC_taxonomy.csv.xz>
#' 
#' - Bird classification information was based on BirdLife, which resulted in 2,391 genus.
#' <http://datazone.birdlife.org/species/taxonomy> However, based on the 
#' [taxonomy file](https://data.vertlife.org/birdtree/BLIOCPhyloMasterTax.csv)
#' of the Jetz et al. 2012 phylogeny, there are additional 117 genus that are not in the file
#' of BirdLife. Both are combined here, which leads to 2,508 genus.
#' 
#' @format A data frame with three columns: genus, family, and taxon (`plant`, `fish`, `bird`). 
#' 
"classifications"

#' Mega-tree of fish from The Fish Tree of Life
#' 
#' This tree was generated by Rabosky et al. (2018). Node labels were added here.
#'
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_fish$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source <https://fishtreeoflife.org/downloads/actinopt_12k_treePL.tre.xz>
#' @references Rabosky, D. L., Chang, J., Title, P. O., Cowman, P. F., Sallan, L., Friedman, M., ... & Alfaro, M. E. (2018). An inverse latitudinal gradient in speciation rate for marine fishes. Nature, 559(7714), 392.
#' 
"tree_fish"

#' Mega-tree of birds from Bird Tree.
#' 
#' This tree was the 288th `set.seed(123); sample(1:1000, 1)` of those 10000 trees with Ericson backbond generated by Jetz et al. (2012). Node labels were added here. This tree will be the default one for bird.
#' 
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_bird_ericson$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source <https://birdtree.org/downloads/>
#' @references Jetz, W., Thomas, G. H., Joy, J. B., Hartmann, K., & Mooers, A. O. (2012). The global diversity of birds in space and time. Nature, 491(7424), 444.
#' 
"tree_bird_ericson"

#' Mega-tree of birds from Bird Tree.
#' 
#' This tree was the 288th `set.seed(123); sample(1:1000, 1)` of those 10000 trees with Hackett backbond generated by Jetz et al. (2012). Node labels were added here.
#' 
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_bird_hackett$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source <https://birdtree.org/downloads/>
#' @references Jetz, W., Thomas, G. H., Joy, J. B., Hartmann, K., & Mooers, A. O. (2012). The global diversity of birds in space and time. Nature, 491(7424), 444.
#' 
"tree_bird_hackett"